# Generated by Django 3.2.6 on 2021-08-05 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('serve_news', '0002_article_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='type',
            field=models.TextField(max_length=100, null=True),
        ),
    ]
